### PR TITLE
added Set support for read and write.

### PR DESCRIPTION
**Pull request by hythl0day**
Just added read and write of Set_dynamic, Set_int, Set_double, Set_String.
Not yet support HiveList like Set of Object. maybe later.

### CODE REVIEW

**Comment by leisim** [comment]
I'm not sure whether this is worth complicating the database code. You can just use a custom adapter to convert Sets to Lists. I don't see a benefit using a completely new type for Sets.

**Comment by TheMisir** [comment]
Adding new internal type adapters might corrupt exists data. I'm not sure about merging this PR.

**Comment by suragch** [comment]
I'd vote for supporting the Set type without the need for a custom adapter.

**Comment by svonidze** [comment]
I could not get neither 
> can be easily worked around using a custom getter/setter or a custom adapter.

working.
1 custom getter/setter
does not work
```
  test('custom getter/setter', () {
    final foo = Foo();
    foo.strings = {'1', '2'};
    foo.strings.add('3');
    print(foo.strings); // {1, 2, 3}
    print(foo._list); // [1, 2]
  });
}

// @HypeType
class Foo {
  Set<String> get strings => _set ?? (_set = _list?.toSet());

  set strings(Set<String> value) {
    _set = value;
    list = value.toList();
  }

  Set<String> _set;
  // @HypeFiled
  List<String> _list;
}
```
`_set` and `_list` are not in sync.
2 custom adapter
I tried to create (and then, of course, registered)
- adapter on `Set<String>`
- adapter on `Set<T>`
- my own implementation of Set and adapter on it

these attempts failed, either due to
- runtime error, HiveGenerator still creates `set: (fields[7] as List)?.cast<String>(),`
- or rebuild error: `Bad state: No element`

@leisim could you provide a working workaround or point to my mistake?

**Comment by Miamoto-Musashi** [comment]
> I'm not sure whether this is worth complicating the database code. You can just use a custom adapter to convert Sets to Lists. I don't see a benefit using completely new `FrameValueType`s for Sets.

Any example to make life easier?

**Pull request closed without merging**
