### PR TITLE
Store int as int64 rather than float64

### PR DESCRIPTION
**Pull request by moffatman**
Address #864 

It's done in a backwards-compatible way, so that existing ints stored as doubles will be read without error, but future values will be stored with full precision. 

A lot of diff from regenerating the test frame data files.

### CODE REVIEW

**Comment by themisir** [comment]
But this implementation does changes behavior for public apis (`readInt` and `writeInt`) which means in some cases this is breaking / backwards incompatible change. Also int64 is not supported on web platform (check [CI output](https://github.com/hivedb/hive/runs/4648329675?check_suite_focus=true) for example), so I think that's the reason why ints implemented using floats since all numbers in web/js are floats.

**Comment by moffatman** [comment]
It wouldn't be breaking if the real int64 was stored as a new typeID, so the old ones would still be read properly. I guess it would be backwards incompatible, if you had this new version, then downgraded. But yeah I thought that int64read etc would just work on web with reduced precision, looks like they would have to be implemented from scratch. Seems like too much work now, so I just used a custom adapter in my own app when I know my values will be greater than 2^53

**Comment by ManInTheWind** [comment]
I ran into this problem too, write as int (7060881601339645953) but read from database is (7060881601339645952)😂

**Comment by Ye-Ethan** [comment]
I ran into this exact same issue on the Android platform. I was wondering, as a potential workaround, could we determine the underlying storage type based on the platform at runtime? For instance, storing it as int64 on native platforms and falling back to double (or even forcing it as a String) on Web?

**Pull request closed without merging**
