### PR TITLE
Prevent non-catchable errors from occurring when opening a box

### PR DESCRIPTION
**Pull request by TheCarpetMerchant**
Leaving hanging Futures that can raise Exceptions like happens to be nasty, because they will not be caught by a try-catch higher up the callstack. They can only get caught by zone-level error handling, which is not great.
This is necessary for my [hive_multiisolate](https://github.com/TheCarpetMerchant/hive_multiisolate) package to function with 100% safety (hopefully).

### CODE REVIEW

**Comment by TheCarpetMerchant** [comment]
@TheOneWithTheBraid Are you handling PRs, or is misir still doing it ?

**Comment by TheCarpetMerchant** [comment]
@themisir Sorry, tagging you due to not seeing any answers.

**Comment by themisir** [comment]
> @themisir Sorry, tagging you due to not seeing any answers.

Np, I left a review message above. Since I didn't heard back from you, I have implemented it myself - https://github.com/hivedb/hive/commit/68b6e62921f0fced82f950ed363c2a415e78e7e6#diff-5405afd0b66478f672f1f6a400d2400403aac2b2993d57fb313a64aaa902cd47R115-R119 ;

**Comment by TheCarpetMerchant** [comment]
> > @themisir Sorry, tagging you due to not seeing any answers.
> 
> Np, I left a review message above. Since I didn't heard back from you, I have implemented it myself - [68b6e62#diff-5405afd0b66478f672f1f6a400d2400403aac2b2993d57fb313a64aaa902cd47R115-R119](https://github.com/hivedb/hive/commit/68b6e62921f0fced82f950ed363c2a415e78e7e6#diff-5405afd0b66478f672f1f6a400d2400403aac2b2993d57fb313a64aaa902cd47R115-R119) ;

Well that's weird, I don't see that anywhere. Can you grab a link to it so I can figure out why I can't find/see that ?

**Comment by TheCarpetMerchant** [comment]
@themisir Also, I just tested your modification and it's not equivalent to this PR and doesn't fix the problem due to `completeError` :/

**Comment by themisir** [comment]
Screenshot 2023-04-10 at 12 48 00 AM

If it's not visible for you it might be my own mistake too - i haven't finished the review, thought you will see the comment anyway. I don't know if github does show comments before finishing the review or not.

Nonetheless, what's your current behavior? Does it work in an unexpected way, or there's something else?

**Comment by TheCarpetMerchant** [comment]
Yeah, not seeing it. Learn something new everyday :)

You can run [this test](https://github.com/TheCarpetMerchant/hive_multiisolate/blob/master/test/test.dart) with hive's master branch to see the problem getting raised. `completeError` will create an exception that cannot be caught, which is why I used `complete` with a boolean (since we rethrow the error, no need to transmit that info through the completer, that would just raise the same error twice. A descriptive message of what happened is better, I feel, so that's what I did in this PR).

As for your review, it's indeed probably better to catch any errors raised by the closing of the box so that it's the original error that gets rethrown. Should I amend this PR ?

**Comment by TheCarpetMerchant** [comment]
@themisir Tagging you :)

**Comment by TheCarpetMerchant** [comment]
@TheOneWithTheBraid Could you consider this PR, please ? Many thanks !

**Comment by themisir** [comment]
Hey sorry for very late reply, I wonder what's the problem with the current implementation. I believe it should throw an error when openBox fails. What's the behavior you are expecting and what's actually happening?

**Comment by TheCarpetMerchant** [comment]
> Hey sorry for very late reply, I wonder what's the problem with the current implementation. I believe it should throw an error when openBox fails. What's the behavior you are expecting and what's actually happening?

The PR as-is does throw an error (see `rethrow`, line 127). The problem is that the exception created by `completeError` will create another exception that cannot be caught because it will be out of this async scope. To prevent this behavior, the PR does a normal `complete` that returns the value `false`, which allows the async scope that was waiting on the box to get opened to raise its own exception, catchable this time.

To see the behavior in action, run the test I mentioned [here](https://github.com/hivedb/hive/pull/1158#issuecomment-1501590542) :)

**Pull request merged**
