### PR TITLE
fix issues

### PR DESCRIPTION
**Pull request by leagmain**
1. quiver dependencies version conficts
2. generated code use experimental features

### CODE REVIEW

**Comment by marcelgarus** [comment]
Is the `dartx` update the same as in PR #318 or #277?
Also, the collection-for feature was introduced [over a year ago](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#230---2019-05-08) and AFAIK it's not experimental anymore.

**Comment by leagmain** [comment]
> Is the `dartx` update the same as in PR #318 or #277?
> Also, the collection-for feature was introduced [over a year ago](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#230---2019-05-08) and AFAIK it's not experimental anymore.

* yes, dartx update as same as #277 .
* I am not clear about the spread-collection feature, I used stable flutter version, it warning me with the auto generated code, I think we should use the common base solution in generated code.
Below is my dart and flutter version:
```
Flutter 1.17.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f7a6a7906b (6 days ago) • 2020-05-12 18:39:00 -0700
Engine • revision 6bc433c6b6
Tools • Dart 2.8.2
```

**Comment by marcelgarus** [comment]
What is the `environment` in your `pubspec.yaml`? It should be something like `sdk: '>=2.7.0 <3.0.0'`.
If it's lower, it's telling Dart "the code in this project should also compile with a Dart SDK of a lower version", which is usually not what you want.

**Comment by leagmain** [comment]
Hi @marcelgarus you are right!
My `environment` is `sdk: ">=2.1.0 <3.0.0"`, and this was generate automatically by flutter.
It's lower that `2.3.0`, which has spread-collection features in dart. It's ok for me, I can accept it now to manually upgrade my `environment` to higher version.

One more question, when do wo plan to release next `hive-generator`?

**Comment by marcelgarus** [comment]
That's a good question. @leisim is the maintainer of this repo (and AFAIK the only person able to `pub lish` the package right now).
He's not been responsive for the past few weeks, but [will be back soon](https://github.com/hivedb/hive/issues/305#issuecomment-628453876), whenever that may be. Then, he could publish a new version. Until then, I guess we just have to wait.

**Comment by leagmain** [comment]
Thanks @marcelgarus nice work with your guys.

**Pull request closed without merging**
