### PR TITLE
Support more types in binary reader and writer

### PR DESCRIPTION
**Pull request by dipu-bd**
This change adds some methods to BinaryWriter, BinaryWriterImpl, BinaryReader and BinaryReaderImpl.
Corresponding test methods are also added to binary_writer_test and binary_reader_test.

New supported types to read and write are:
- Uint8
- Int8
- Uint16
- Int16
- BigInt

Also, _peekSomething()_ could be a useful feature.
Added support to peek values for most of the easily accessible types.

### CODE REVIEW

**Comment by leisim** [comment]
@dipu-bd Thanks for this PR. I think the peek... methods are quite useful but I'm not convinced by the `readUint8()` and `readUint16()` because there are already a `readByte()` and  `readWord()` methods. Also I think `readInt8()` and `readInt16()` are not really needed because they will be used very rarely. The same goes for the corresponding write methods.

A `readBigInt()` is also not needed because Hive knows how to read and write BigInts and you can just use `read()` and `write()`

**Comment by dipu-bd** [comment]
@leisim It is true that readByte and readWord can do the job. I am actually using those methods inside readUint8 and readUint16. But since there is support for readInt8 and readInt16, it makes sense to provide corresponding unsigned integer versions of these methods.

nvm I did not know that BigInt was supported directly by read() and write(). I will update this PR

**Comment by leisim** [comment]
I would not support `readInt8` and `readInt16`. I find it unlikely that there is a need to save an extra two or three bytes compared to `readInt32()`.

**Comment by dipu-bd** [comment]
For a single integer, it really does not matter if I am using 32 bit or 16bit. But what if I want to store an array of 16-bit integers? It would increase the size unnecessarily.

**Comment by leisim** [comment]
Just use `ByteData` and write the bytes to the `BinaryWriter`.

**Comment by dipu-bd** [comment]
I thought it would be cool to have Int8 and Int16 too, since ByteData also have them. 

Should I update this PR removing them and keeping only _peek...._ methods? Or, close it altogether?

**Pull request closed without merging**
