### PR TITLE
fix: support collections in deleteFromDisk

### PR DESCRIPTION
**Pull request by TheOneWithTheBraid**
- do not delete entire database in case only one objectStore to be
  deleted

Signed-off-by: TheOneWithTheBraid <the-one@with-the-braid.cf>

### CODE REVIEW

**Comment by TheOneWithTheBraid** [comment]
I would appreciate an update on pub.dev.

**Comment by themisir** [comment]
> I would appreciate an update on pub.dev.

Can you write a small sentence describing changes being done on this patch (needed for changelog)? :D I didn't understand what exactly this patch is going to do, otherwise I would write it myself

**Comment by TheOneWithTheBraid** [comment]
This fix properly supports deleting BoxCollections on web respecting whether there are different object stores stored in.

**Comment by TheOneWithTheBraid** [comment]
Done with https://github.com/hivedb/hive/pull/976.

**Pull request merged**
