### PR TITLE
feat: Add flush method to boxes

### PR DESCRIPTION
**Pull request by Sorunome**
This PR adds a flush method to boxes to be able to manually flush them to the disk. If utilized correctly, this would solve #263

### CODE REVIEW

**Comment by yasargil** [comment]
@themisir could you look in to this we are very interested in trying this out in our next app release which is scheduled soon.

**Comment by yasargil** [comment]
Perhaps in the compact method https://github.com/hivedb/hive/blob/072108620d35914df09567b0ac5540cb0dce11e6/hive/lib/src/backend/vm/storage_backend_vm.dart#L145 bevor start reading there should be a flush to the writer?

**Comment by Sorunome** [comment]
while compact does call `.flush()` it also does way more, which is why it wouldn't be that ideal for performance. You wouldn't have to call it *before* making a write, but *after* making a write.

**Comment by Sorunome** [comment]
For reference, [this](https://gitlab.com/famedly/company/frontend/libraries/fluffybox/-/blob/soru/fix-db-corruption/lib/src/native.dart#L61-82) is our thin layer at work, how we utilize this PR

**Comment by yasargil** [comment]
Compact uses the reader (readRaf) to read alle frames, so there is the possibility that the writer (writeRaf) has some unwritten bytes in the buffer when a compact is executed, even when i would use your flush after writing my data there is no guarantee that this flush comes bevor the compact operation. 

I think it would be best to ensure all bytes are written bevor `await readRaf.setPosition(0);` in the compact method.

**Comment by Sorunome** [comment]
That is unneeded, the kernel takes care of if a file should be flushed to disk or not, and thus, as long as the application is running normally, you don't have to call `.flush()`. The issue comes if the application unexpectedly stops, meaning that there could be pending changes left in-memory which have not been flushed to disk yet.

**Comment by yasargil** [comment]
Interesting so you say `await readRaf.setPosition(0);` will trigger the operating system to flush all bytes from the writeRaf? Then my assumption is indeed invalid.

**Comment by Sorunome** [comment]
No, is saying that it does not matter for `.compact()` if the changes are flushed to disk or not, as the kernel abstracts that layer mostly away.

**Comment by yasargil** [comment]
ah yes i see it now. thank you and sry for hijacking your pr for some lessons on RandomAccessFiles

**Comment by themisir** [comment]
Interesting findings! Do you have any idea if we could setup an environment to test if flushing does solve corruption issue? In theory it should but real life is complicated so I'm thinking if we could test it out at least..

**Comment by Sorunome** [comment]
We did already test it and adding flushing after writing fixed it for us. To test it reliably you basically have to unexpectedly kill the system, so you might want to use a VM for that. Something like `echo b > /proc/sysrq-trigger` should do the trick.

What we did was verify a bunch of such resets with flushing, and it did not corrupt the database at all, while without flushing it did corrupt quite frequently (not 100% of the time, though, as is with the nature of such things)

**Review by themisir — APPROVED** [review]
LGTM

**Comment by Sorunome** [comment]
Thank you for the quick merge! 👍 Please do keep in mind that people will have to utilize the added flush method correctly, as outlined here: https://github.com/hivedb/hive/issues/263#issuecomment-986647310

**Comment by themisir** [comment]
> It might make sense to add auto-flush after every put or something as an easy method, but that ought to impact performance quite a bit

Yes exactly I thought that too, but then thought it might cause performance issues, so a transaction like extension would be much better for people to run transaction in a callback and when execution completes it automatically flushes updates. But that could be added later on but until then users could write a extension like that:

```dart
extension HiveX on BoxBase {
  Future<void> transaction(FutureOr<void> txn()) async {
    try {
      await txn();
    } finally {
      this.flush();
    }
  }
}
```

**Comment by Sorunome** [comment]
Yeah. At work we usually operate on multiple boxes at once, which is why our solution currently is [this](https://gitlab.com/famedly/company/frontend/libraries/fluffybox/-/blob/soru/fix-db-corruption/lib/src/native.dart#L61-82) where it additionally automatically collects which boxes it does write operations on, using dart execution zones. Maybe something like that could also be added here, with like

```dart
await Hive.transaction(() async {
  // write operations on multiple boxes
});
```

**Pull request merged**
