### PR TITLE
[WIP] DO NOT MERGE: Migrate hive to dart nnbd

### PR DESCRIPTION
**Pull request by KalilDev**
For now, package:hive was migrated, and every test passes, but there are some hacks on the test's codegen and package:crypto and package:mockito have been overriden with git versions which were not published on pub.dev. The tests also depend on the legacy package:dartx and package:pointycastle, so they can only be ran with --no-sound-null-safety.

The release is blocked until at least package:crypto has an published non-nullable version.

Ill start working on the hive_generator, as hive needed to be migrated first because it is an direct dependency of the packages which would use the generator.

### CODE REVIEW

**Comment by KalilDev** [comment]
Alright, what do you think about the nullability in the hive api?

**Comment by leisim** [comment]
Wow, amazing work! Looks very good. I'll review the changes in detail as soon as possible :+1:

**Comment by KalilDev** [comment]
Alright!

**Comment by TheMisir** [comment]
Very good 👌

**Comment by KalilDev** [comment]
Oh, i just realized i did not look into the chrome tests and the integration tests. Ill fix the failed ones and do some touch ups on their migration, so sorry.

**Comment by TheMisir** [comment]
> Oh, i just realized i did not look into the chrome tests and the integration tests. Ill fix the failed ones and do some touch ups on their migration, so sorry.

No problem 👍

**Comment by KalilDev** [comment]
Hmm, while testing on chrome, i could not run with --no-sound-null-safety, so im fixing the errors with sound null safety, and i noticed some that are unfixable with the current Hive implementation and mockito non nullable api. For now im documenting those cases and i opened an issue on mockito with some suggestions that would help with the testing and fixing these cases. https://github.com/dart-lang/mockito/issues/305

**Comment by KalilDev** [comment]
Alright, i had to add a lot of stubs to fix the web (sound null safety) tests, so i ended up also fixing the remaining VM tests. Outside of the files which import non migrated packages, every test passes on sound null safety. The tests became a lot more verbose tho, because every call that returns an non nullable value needs to be stubbed with mockito on nnbd. This is prime for refactoring.

**Comment by FelixMittermeier** [comment]
@KalilDev Wow sounds really great. Thank you so much for your work ☺️🎉

**Comment by KalilDev** [comment]
So, both crypto(3.0.0-nullsafety.0) and mockito(5.0.0-nullsafety.1) got published to pub.dev . I tested removing the dependency overrides and pinning the new versions, and there was an dependency conflict: `Because mockito >=4.1.2 depends on build ^1.3.0 which depends on crypto >=0.9.2 <3.0.0, mockito >=4.1.2 requires crypto >=0.9.2 <3.0.0.
So, because hive depends on both crypto ^3.0.0-nullsafety.0 and mockito ^5.0.0-nullsafety.1, version solving failed.`

Soo, yeah, we are now waiting on `build` upgrading the `crypto` dependency [here](https://github.com/dart-lang/build/blob/dff700f952f56bcd785d5a3d981ec5cff045cd3c/build/pubspec.yaml#L13), and then on `mockito` upgrading the `build` dependency.

**Comment by DrasiusMajere** [comment]
crypto and mockito have already done their null-safety version

**Comment by KalilDev** [comment]
> crypto and mockito have already done their null-safety version

We were being blocked by package:build, but apparently we aren't anymore: https://github.com/dart-lang/build/commit/1cc434bf33db18117797ea9517a6129f70f8394a

**Comment by KalilDev** [comment]
Well, i suppose i will migrate the hive_generator now. package:hive seems complete

**Comment by KalilDev** [comment]
[Tests for the codegen](https://github.com/KalilDev/hive_nnbd_codegen_test/commit/4c62ad56a93c42ec45b1212286ea10d74ffca41e) are looking good. Didn't find an problem reviewing it manually, and `dart analyze` does not complain either.

**Comment by KalilDev** [comment]
@TheMisir soo, only hive_flutter remains to be migrated, and the current version for it is 0.3.1, and according to [dart.dev](https://dart.dev/null-safety/migration-guide#package-version), the new version can either be 0.4.0-nullsafety.0 or 1.0.0-nullsafety.0. which one will we go with? The same for hive_generator, which is 0.8.2 and can be either 0.9.0-nullsafety.0 or 1.0.0-nullsafety.0.

And, should we finish reviewing and publishing the core packages (hive and hive_generator) before migrating hive_flutter, or should i migrate it in this PR?

Im waiting for further instructions so we can move hive forward!

**Comment by TheMisir** [comment]
> @TheMisir soo, only hive_flutter remains to be migrated, and the current version for it is 0.3.1, and according to [dart.dev](https://dart.dev/null-safety/migration-guide#package-version), the new version can either be 0.4.0-nullsafety.0 or 1.0.0-nullsafety.0. which one will we go with? The same for hive_generator, which is 0.8.2 and can be either 0.9.0-nullsafety.0 or 1.0.0-nullsafety.0.
> 
> And, should we finish reviewing and publishing the core packages (hive and hive_generator) before migrating hive_flutter, or should i migrate it in this PR?
> 
> Im waiting for further instructions so we can move hive forward!

I think increasing major version (1.X.Y+nullsafety.Z) will work for us cause the new library will not be compatible with previous version because it requires explicitly enabling NNBD. Correct me if I'm wrong.

And about `hive_flutter` we can either work on it later or publish them all at once. It doesn't matter I think.

Also I have a question. I haven't worked on null-safety enabled projects before so, will the NNBD version work with the previous versions of the flutter or dart? I mean at least currently stable versions (which comes with NNBD disabled). Or we'll have to maintain nndb and non-nndb codebase separately?

(I've inspected some of flutter's own source code on my localhost, currently my flutter environment set to not use NNBD but flutter source code contains NNDB code.) If you have any idea about that please let me know. 🙏

**Comment by felangel** [comment]
> the new version can either be 0.4.0-nullsafety.0 or 1.0.0-nullsafety.0. which one will we go with? The same for hive_generator, which is 0.8.2 and can be either 0.9.0-nullsafety.0 or 1.0.0-nullsafety.0.

I would recommend `0.4.0-nullsafety.0` and `0.9.0-nullsafety.0` because dart semver will treat those a major version bumps (since the version is less than 1.0.0) so a 1.0.0 release is not necessary.

> And about hive_flutter we can either work on it later or publish them all at once. It doesn't matter I think.

It would be great if nullsafety releases could be published as soon as possible for `hive` and `hive_generator` so that other packages which depend on them can start migrating right away.

**Comment by felangel** [comment]
After testing these changes I think I've found a bug in `Hive.close()`.

I would expect the following to be valid:

```dart
Hive.init(path);
await Hive.close();

Hive.init(path); // this throws HiveError: Instance has already been initialized.
await Hive.close();
```

This could be solved by resetting the `homePath` to null when `close` is called at https://github.com/hivedb/hive/pull/521/files#diff-5405afd0b66478f672f1f6a400d2400403aac2b2993d57fb313a64aaa902cd47L207.

```dart
  @override
  Future<void> close() {
    var closeFutures = _boxes.values.map((box) {
      return box.close();
    });

    homePath = null;
    return Future.wait(closeFutures);
  }
```

Let me know what you think 👍

**Comment by TheMisir** [comment]
> After testing these changes I think I've found a bug in `Hive.close()`.
> 
> I would expect the following to be valid:
> 
> ```dart
> Hive.init(path);
> await Hive.close();
> 
> Hive.init(path); // this throws HiveError: Instance has already been initialized.
> await Hive.close();
> ```
> 
> This could be solved by resetting the `homePath` to null when `close` is called at https://github.com/hivedb/hive/pull/521/files#diff-5405afd0b66478f672f1f6a400d2400403aac2b2993d57fb313a64aaa902cd47L207.
> 
> ```dart
>   @override
>   Future<void> close() {
>     var closeFutures = _boxes.values.map((box) {
>       return box.close();
>     });
> 
>     homePath = null;
>     return Future.wait(closeFutures);
>   }
> ```
> 
> Another option would be to revert [59ad540#r46404472](https://github.com/hivedb/hive/commit/59ad5403593283233d922f62f76832c64fa33a3b#r46404472) as it introduces a breaking change and no longer allows for multiple Hive instances to exist simultaneously.
> 
> Let me know what you think 👍

Initializing hive multiple times causes weird errors. So Instead of initializing it multiple times you can construct `HiveImpl` instance and use it.

```dart
var hive1 = HiveImpl();
hive1.init(path);
await hive1.close();

var hive2 = HiveImpl();
hive2.init(path);
await hive2.close();
```

**Comment by felangel** [comment]
@TheMisir thanks for the clarification! Is there anything blocking a release of `hive` and `hive_generator`? It's currently blocking https://github.com/felangel/bloc/pull/2117.

**Comment by KalilDev** [comment]
> > the new version can either be 0.4.0-nullsafety.0 or 1.0.0-nullsafety.0. which one will we go with? The same for hive_generator, which is 0.8.2 and can be either 0.9.0-nullsafety.0 or 1.0.0-nullsafety.0.
> 
> I would recommend `0.4.0-nullsafety.0` and `0.9.0-nullsafety.0` because dart semver will treat those as major version bumps (since the version is less than 1.0.0) so a 1.0.0 release is not necessary.
> 
> > And about hive_flutter we can either work on it later or publish them all at once. It doesn't matter I think.
> 
> It would be great if nullsafety releases could be published as soon as possible for `hive` and `hive_generator` so that other packages which depend on them can start migrating right away.

Alright, thanks for the tip! I will promptly update the versions and write a changelog for the packages.



> @TheMisir thanks for the clarification!
> 
> Is there anything blocking a release of `hive` and `hive_generator`? It's currently blocking [felangel/bloc#2117](https://github.com/felangel/bloc/pull/2117). Let me know if I can help in any way 👍

I think there isn't, the tests are passing, including the integration tests, and the hive_generator code looks good, but i haven't tested the new hive manually in an real enviroment. If you could, that would be of great help, ensuring that it can be merged safely, otherwise i can do it after the deadline im in.

I'm sorry for the late response, these days i've been busy with an deadline for 02/01, so i haven't had the time to follow up this pr.

**Comment by felangel** [comment]
@TheMisir no problem I completely understand! I’ve upgraded hydrated_bloc to use this version and everything seems to be working 👍

**Comment by TheMisir** [comment]
> @TheMisir thanks for the clarification!
> 
> Is there anything blocking a release of `hive` and `hive_generator`? It's currently blocking https://github.com/felangel/bloc/pull/2117. Let me know if I can help in any way 👍 

    I'll work on this pr today. And publish if everything goes okay.

**Comment by TheMisir** [comment]
I've just completed testing `hive` and `hive_generator`. 

@KalilDev may you upgrade minor version instead of major as @felangel said? I'll merge this PR after that.

> I would recommend 0.4.0-nullsafety.0 and 0.9.0-nullsafety.0 because dart semver will treat those as major version bumps (since the version is less than 1.0.0) so a 1.0.0 release is not necessary.

**Comment by KalilDev** [comment]
> I've just completed testing `hive` and `hive_generator`.
> 
> @KalilDev can you upgrade minor version instead of major as @felangel said? I'll merge this PR after that.
> 
> > I would recommend 0.4.0-nullsafety.0 and 0.9.0-nullsafety.0 because dart semver will treat those as major version bumps (since the version is less than 1.0.0) so a 1.0.0 release is not necessary.

I just pushed hive_generator to 0.9.0-nullsafety.0, [here](https://github.com/hivedb/hive/pull/521/commits/a898caeadf51414416b4f899c4d0ae0dc3e057cb), is there anything else left?

**Comment by TheMisir** [comment]
Nevermind I'll do it myself after merging. Thanks for the contribution 🙏

**Comment by KalilDev** [comment]
> @KalilDev
> 
> Can you also set `hive` version to `1.6.0-nullsafety.0`?

Oh, sorry, i had to leave home for a bit.



> Nevermind I'll do it myself after merging. Thanks for the contribution pray

Alright!! No problem, man! Thanks for merging!

**Comment by TheMisir** [comment]
> Oh, sorry, i had to leave home for a bit.

No problem ✌

**Comment by TheMisir** [comment]
@KalilDev may I know how did you setup your environment (flutter cli, vscode, etc...) to use null safety? I couldn't setup mine :(

**Comment by KalilDev** [comment]
> @KalilDev may I know how did you setup your environment (flutter cli, vscode, etc...) to use null safety? I couldn't setup mine unfortunately :(

For it to work `dart --version` needs to be greater or equal to 2.12.0. For that i'm using the dart sdk from flutter on the master channel, but it works with the beta channel too. The `dart` executable that flutter ships is in `$yourFlutterRoot/bin/cache/dart-sdk/bin/`, so that folder needs to be in $PATH

I'm using vscode as the ide, and for using nnbd hive on a package, the dart sdk constraint needs to be >= 2.12.0-0 and the hive dependency needs to be overriden with the following pubspec entries:

```
dependencies:
  hive: ^1.6.0-nullsafety.0

dev_dependencies:
  hive_generator: ^0.9.0-nullsafety.0

dependency_overrides:
  hive:
    git:
      url: git@github.com:hivedb/hive.git
      ref: nnbd
      path: hive
  hive_generator:
    git:
      url: git@github.com:hivedb/hive.git
      ref: nnbd
      path: hive_generator
```

**Pull request merged**
