### PR TITLE
Change `HiveError` to `HiveException`

### PR DESCRIPTION
**Pull request by unacorbatanegra**
I change the `Error` to `Exception` because `Error` should not be use on try catch.
Maybe have to be a mix between the two types to use properly each of one.

### CODE REVIEW

**Comment by TheMisir** [comment]
But it's gonna be a breaking change. Also, I don't think ..Error naming is strictly applied among the dart ecosystem. Other packages also sometimes use Error naming (eg: `package:dio/dio.html`).

**Comment by unacorbatanegra** [comment]
But `Error` should be use to help development process,  and `Exception` to handle it on try catch, if there's an error on Runtime , should be appear as an Exception.
In any case this is an idea and a guideline, you can use Error, but would be nice if we have an proper Exception when runtime errors appear, even if is a breaking change.

**Comment by TheMisir** [comment]
> But `Error` should be use to help development process, and `Exception` to handle it on try catch, if there's an error on Runtime , should be appear as an Exception.
> In any case this is an idea and a guideline, you can use Error, but would be nice if we have an proper Exception when runtime errors appear, even if is a breaking change.

I totally get your thoughts. But those minor breaking changes usually disturbs package users.

If we could make the change seamless it would be much easier for package users to implement the change over time.

We could define a `typedef HiveError = HiveException` and annotate it with `@deprecated` annotation but type alias feature is only available after dart 2.13 which means upgrading sdk version will be another breaking change. So we have to look for another ways.

WDYT about this?

```dart
@Deprecated('Use `HiveException` instead')
class HiveError {
 ...
}

class HiveException extends HiveError {
 ...
}
```

We can keep HiveError around and extend HiveException from it to make sure `error is HiveError` checks will continue to work, but we use `HiveException` internally. This will let users to apply the change over time seamlessly.

**Comment by unacorbatanegra** [comment]
Looks good to me, I apply it on the commits above

**Comment by unacorbatanegra** [comment]
If anything else need to change to approve this pr, please let me know

**Comment by TheMisir** [comment]
> If anything else need to change to approve this pr, please let me know

Nothing, I just want someone else also review this changes to make sure it wont make so much trouble for users. For example `error.runtimeType = HiveError` checks will going to fail but I don't know if this pattern (type check with `.runtimeType` property) used much or not.

--

cc @mbaumgartenbr can you too please review this changes if you're available?

**Comment by unacorbatanegra** [comment]
The most common thing user will have is a 
```dart
try{
  throw HiveException('This is an exception');
} on HiveError catch(e,s){
   print(e is HiveError); // true
   print(e is HiveException); //true

}
```
When we throw an exception, and the user handle `HiveError`, the `HiveException` will be capture properly, with no breaking changes, I don't know in which cases `error.runtimeType==HiveError` will be useful, for good practices in any case you should use the `is` operator.

**Comment by mbaumgartenbr** [comment]
In my opinion `HiveError` is acceptable because it is a database error, not any conventional exception we have normally, it should be treated differently. I'm not against the renaming,  but I think it is not that important to do.

If you think the `runtimeType` problem would break many codebases, we should delay the renaming to the next "major" release.

We should probably get the community involved for this one...

**Comment by TheMisir** [comment]
> In my opinion HiveError is acceptable because it is a database error, not any conventional exception we have normally, it should be treated differently. I'm not against the renaming, but I think it is not that important to do.

I also thought this last night before going to sleep lol. By default Hive will not throw any error or exception. It'll only do when the developer does something wrong like not registering an adapter or doing serialization or deserialization wrongly.

I also think this needs community involvement. I really don't want to break exists implementations since I personally get annoyed when same think happens to me.

**Comment by unacorbatanegra** [comment]
But actually happens, 
image
This happen to me the other day and broke a production app

**Comment by unacorbatanegra** [comment]
The same code at development time works perfectly, but break a some point, and we must have a proper way to handle if there's any error.

**Comment by mbaumgartenbr** [comment]
> The most common thing user will have is a 
> ```dart
> try{
>   throw HiveException('This is an exception');
> } on HiveError catch(e,s){
>    print(e is HiveError); // true
>    print(e is HiveException); //true
> }
> ```
> When we throw an exception, and the user handle `HiveError`, the `HiveException` will be capture properly, with no breaking changes, I don't know in which cases `error.runtimeType==HiveError` will be useful, for good practices in any case you should use the `is` operator. 
> 
> 

Since Hive is broadly used, we must account for all scenarios.

**Comment by unacorbatanegra** [comment]
> But it's gonna be a breaking change. Also, I don't think ..Error naming is strictly applied among the dart ecosystem. Other packages also sometimes use Error naming (eg: `package:dio/dio.dart`).
> 
> What's your thoughts on that?

Dio use errors, because already handle any exceptions on the interceptor, and just pass the error for you to check it, 
and it's also different because have error types, and many ways to identify when the error happen and why, not only a message.

**Pull request closed without merging**
