### PR TITLE
Added enum_adapters

### PR DESCRIPTION
**Pull request by Afsar-Pasha**
Added enum adapters

- EnumAdapter
  > Saves enum as short string Days.Monday => "Monday"
- EnumLongAdapter
  > Saves enum as long string Days.Monday => "Days.Monday"
- EnumIndexAdapter
  > Saves index of the enum

It can be used as
```dart
Hive.registerAdapter(EnumAdapter(E.values), id)
```

### CODE REVIEW

**Comment by Afsar-Pasha** [comment]
Tests have not been written.
If this can be merged then I can write tests.

**Comment by leisim** [comment]
Enums can already be stored using `hive_generator`. What is the advantage of your approach?

**Comment by Afsar-Pasha** [comment]
Easy to setup and can be used to store `enum`s from different library/package(I think it's not possible in `hive_generator`).

**Comment by leisim** [comment]
I'm going to close this for now since I think more than one way to store enums will confuse most users. If there are others who need to store external enums, we can think about how to solve this...

**Comment by kaciula** [comment]
I like the approach of storing enums this way. For me it's important that my models are not polluted with db details and I would much prefer not to have to add Hive annotations for my model enums.

**Comment by Jictyvoo** [comment]
I like this approach too, looks so simple as Hive looks to be

**Pull request closed without merging**
