### PR TITLE
fix: Created path using collection names

### PR DESCRIPTION
**Pull request by krille-chan**

### CODE REVIEW

**Comment by themisir** [comment]
Is there a chance that this change might break existing apps or was it malfunctioning anyways?

**Comment by krille-chan** [comment]
> Is there a chance that this change might break existing apps or was it malfunctioning anyways?

Unfortunately it is already somehow broken.

regarding the paths we are using the getApplicationDocumentsDirectory() + "/subdirectoryname/" 

So Hive stable stores our boxes at:

"/data/user/0/com.famedly.talk.debug/app_flutter/subdirectoryboxname.hive"
So it truncates the slash and adds it as a prefix to the file name.
And Hive main branch:
"/data/user/0/app.id.meow/app_flutter/subdirectorycollectionname/boxname.hive"

So it is already broken if you migrate from Hive stable to Hive main. This now fixes it in a way that it makes sure the path will be:

"/data/user/0/app.id.meow/app_flutter/subdirectory/collectionname/boxname.hive"

So BoxCollections which want to migrate from current Hive stable (The version in pub.dev) to the current main will have to provide a migration somehow. But as BoxCollections are not marked as stable yet anyway it might be enough to mention it in the next changelog

**Comment by themisir** [comment]
Thank you for the explanation. One small suggestion: can we utilize `dart:path` library to join paths instead of manipulating the string ourselves.

Because, paths are weird in cross platform context (eg: windows uses `\` while unix systems use `/` for path separation).

I know this is not exactly related to your patch, but it would be generally useful. If you don't have time, let me know so I can patch it myself.

**Comment by TheOneWithTheBraid** [comment]
@themisir Afaik the MR attempting to fix the trailing slash intoduced this regression. I don't see how this should break, though, we could test it on master branch for a while before releasing. We internally tested it and it works.

**Pull request merged**
